In [3]:
import numpy as np
#in case we need to repeat experiment
np.random.seed(255)

import pandas as pd
pd.options.display.max_rows = 22

import matplotlib.pyplot as plt
plt.style.use('classic')


import seaborn as sns
sns.set()

In [4]:
#df = pd.read_csv('NCDB_2016.csv', engine = 'python')
df = pd.read_csv('data01_simple.csv', engine = 'python')
#df = pd.read_csv('data01_simple_100.csv', engine = 'python')
df

C_YEAR  C_MNTH  C_WDAY  C_HOUR  C_VEHS  C_CONF  C_RCFG  C_WTHR  \
0          1999       1       1       9       2      34       2       1   
1          1999       1       1       9       2      34       2       1   
2          1999       1       1      20       1       3       3       1   
3          1999       1       1       5       2       1       2       3   
4          1999       1       1       5       2       1       2       3   
5          1999       1       1       8       3      33       2       4   
6          1999       1       1       9       2       1       2       1   
7          1999       1       1      14       2      21       2       1   
8          1999       1       1      14       2      21       2       1   
9          1999       1       1       7       1       4       5       1   
10         1999       1       1      13       2      24       3       1   
...         ...     ...     ...     ...     ...     ...     ...     ...   
3655323    2016      12       7      14       3      21       2       1   
3655324    2016      12       7      14       3      21       2       1   
3655325    2016      12       7      11       1      33       2       1   
3655326    2016      12       7       1       2      21       1       2   
3655327    2016      12       7       1       2      21       1       2   
3655328    2016      12       7       1       2      21       1       2   
3655329    2016      12       7      14       1      34       2       1   
3655330    2016      12       7      12       2      21       1       4   
3655331    2016      12       7      12       2      21       1       4   
3655332    2016      12       7      12       2      21       1       4   
3655333    2016      12       7      12       2      21       1       4   

         C_RSUR  C_RALN   ...    V_ID  V_TYPE  V_YEAR  P_ID  P_SEX  P_AGE  \
0             1       1   ...       1       1    1992     1      0     33   
1             1       1   ...       2       1    1992     1      0     70   
2             1       3   ...       1       1    1988     1      0     38   
3             2       4   ...       1       6    1995     1      1     34   
4             2       4   ...       1       6    1995     2      1     30   
5             2       4   ...       1       1    1989     1      1     18   
6             1       1   ...       1       1    1986     1      0     68   
7             2       1   ...       2       1    1990     1      0     28   
8             2       1   ...       2       1    1990     2      1     37   
9             5       1   ...       1       6    1994     1      0     50   
10            1       1   ...       1       1    1992     1      1     20   
...         ...     ...   ...     ...     ...     ...   ...    ...    ...   
3655323       1       1   ...       3       6    2013     1      1     54   
3655324       1       1   ...       3       6    2013     2      0     55   
3655325       1       1   ...       1       6    2014     1      1     64   
3655326       1       1   ...       1       1    1998     1      1     38   
3655327       1       1   ...       1       1    1998     2      0     39   
3655328       1       1   ...       2       1    2004     1      1     26   
3655329       1       2   ...       1       1    2004     1      0     18   
3655330       3       1   ...       1       1    2012     1      0     44   
3655331       3       1   ...       2       1    2010     1      1     31   
3655332       3       1   ...       2       1    2010     2      0     25   
3655333       3       1   ...       2       1    2010     3      0      1   

         P_PSN  P_SAFE  P_USER  P_ISEV  
0           11       2       1       2  
1           11       2       1       1  
2           11       2       1       2  
3           11       2       1       1  
4           13       2       2       1  
5           11       2       1       2  
6           11       2       1       1  
7           11       2       1 

In [5]:
df.isnull().sum().sum()

0

In [6]:
df[df.index.astype('str').str.contains('[^0-9]')].sum().sum()

0

In [7]:
df_cat = df.astype('category').copy()


In [8]:
df_int = df.astype('int').copy()

In [9]:
df_cat_n = df_cat[:100000]

In [10]:
print(df.columns)

Index(['C_YEAR', 'C_MNTH', 'C_WDAY', 'C_HOUR', 'C_VEHS', 'C_CONF', 'C_RCFG',
       'C_WTHR', 'C_RSUR', 'C_RALN', 'C_TRAF', 'V_ID', 'V_TYPE', 'V_YEAR',
       'P_ID', 'P_SEX', 'P_AGE', 'P_PSN', 'P_SAFE', 'P_USER', 'P_ISEV'],
      dtype='object')


0          False
1          False
2          False
3          False
4          False
5          False
6          False
7          False
8          False
9          False
10         False
           ...  
3655323    False
3655324    False
3655325    False
3655326    False
3655327    False
3655328    False
3655329    False
3655330    False
3655331    False
3655332    False
3655333    False
Name: P_ISEV, Length: 3655334, dtype: bool
0


In [ ]:
## Split Data into each class

In [ ]:
type(df_cat['P_ISEV'])
df_cat['P_ISEV']

# fatal
is_fatal =  df_cat['P_ISEV']==3
#print(is_fatal)
is_fatal_count = is_fatal.sum()
print(is_fatal_count)
df_cat_fatal = df_cat[is_fatal]
display(df_cat_fatal)


In [ ]:
# injury
is_injury =  df_cat['P_ISEV']==2
#print(is_injury)
is_injury_count = is_injury.sum()
print(is_injury_count)
df_cat_injury = df_cat[is_injury]
display(df_cat_injury)


In [ ]:
# non_injury
is_safe =  df_cat['P_ISEV']==1
#print(is_safe)
is_safe_count = is_safe.sum()
print(is_safe_count)
df_cat_safe = df_cat[is_safe]
display(df_cat_safe)

In [48]:
# get the size of fatal datafram
min_size = df_cat_fatal.index.size
print(min_size)

23081


In [49]:
# get size of injury
df_cat_safe.index.size

1570775

In [50]:
# size of injury
df_cat_injury.index.size

2061478

In [51]:
# randomly sample n number of injury and no injury and append to fatal
df_cat_injury_select = df_cat_injury.sample(n=min_size)
df_cat_safe_select = df_cat_safe.sample(n=min_size)


In [52]:
df_cat_injury_select.shape

(23081, 21)

In [54]:
df_cat_safe_select.shape

(23081, 21)

In [56]:
#concat the three dataframes
df_final = pd.concat([df_cat_fatal, df_cat_injury_select, df_cat_safe_select])
df_final.shape

(69243, 21)

In [57]:
#Split between train and test

Y = df_final[df_cat.columns[-1]]
X = df_final[df_cat.columns[0:df_cat.columns.size -1]]
X

C_YEAR C_MNTH C_WDAY C_HOUR C_VEHS C_CONF C_RCFG C_WTHR C_RSUR C_RALN  \
75        1999      1      1     22      1      2      1      1      1      1   
213       1999      1      1     20      2     35      2      3      2      1   
291       1999      1      1     11      2     31      1      1      5      4   
292       1999      1      1     11      2     31      1      1      5      4   
293       1999      1      1     11      2     31      1      1      5      4   
417       1999      1      1     10      2     21      2      4      3      2   
419       1999      1      1     12      2      1      5      1      2      1   
424       1999      1      1     22      2     31      1      4      3      1   
425       1999      1      1     16      3     31      1      1      1      1   
427       1999      1      1     16      3     31      1      1      1      1   
429       1999      1      1     17      1      1      1      4      3      1   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2355971   2009     10      5     12      3     35      2      1      2      2   
1237806   2004      5      5      6      2     22      1      1      1      1   
1306974   2004      9      1     12      2     22      1      1      1      1   
2978032   2013      3      1      8      1      6      3      1      5      1   
1492701   2005      7      4     12      1      6      2      1      1      1   
1220823   2004      4      4      8      2     21      2      1      1      1   
3249447   2014      9      6      8      2     33      2      1      1      1   
1088738   2003      9      3     17      2     21      1      2      1      1   
792471    2002      6      5     10      1      2      1      1      1      2   
734624    2002      3      3     12      2     33      2      1      1      1   
222589    1999     12      6     18      2     21      2      3      2      2   

        C_TRAF V_ID V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_SAFE P_USER  
75          18    1      1   1991    1     1    74    11      2      1  
213          1    1      6   1990    1     1    60    11     13      1  
291         18    2      1   1988    1     1    30    11      2      1  
292         18    2      1   1988    2     0    27    13      2      2  
293         18    2      1   1988    3     1     7    23      2      2  
417         18    1      1   1993    2     0    58    13      2      2  
419         18    1      1   1991    1     1    42    11      2      1  
424         18    2      1   1986    2     0    54    13      2      2  
425         18    1      1   1998    1     0    71    11      2      1  
427         18    2      1   1992    2     0    84    13      2      2  
429         18    1      1   1997    1     1    69    11      2      1  
...        ...  ...    ...    ...  ...   ...   ...   ...    ...    ...  
2355971      3    3      7   1996    1     1    49    11      2      1  
1237806     18    2      8   2000    1     1    27    11      2      1  
1306974     18    2      1   2002    1     0    33    11      2      1  
2978032     18    1      1   2003    1     0    31    11      2      1  
1492701      3    1      1   1999    1     1    46    11      2      1  
1220823      1    1      1   2001    1     1    22    11      2      1  
3249447     18    2      1   2003    1     1    52    11      2      1  
1088738     18    2      1   1991    1     1    17    11      2      1  
792471      18    1      1   1996    1     1    29    11      2      1  
734624       1    2      1   1998    1     0    40    11      2      1  
222589       1    1      1   1994    1     0    29    11      2      1  

[69243 rows x 20 columns]

In [58]:
#sprint into train and test 70/30
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [59]:
display(X_test, Y_test)
display(X_train, Y_train)

C_YEAR C_MNTH C_WDAY C_HOUR C_VEHS C_CONF C_RCFG C_WTHR C_RSUR C_RALN  \
1797192   2006     12      2      6      2     33      1      1      1      1   
704891    2002      1      4     17      3     21      1      2      1      1   
86650     1999      6      2     16      2     21      1      1      1      1   
932017    2003      1      1      8      2     21      3      1      2      1   
3131694   2014      1      2      8      2     31      1      1      2      2   
3114604   2013     12      1     11      1      2      1      1      3      1   
1746683   2006      9      4      8      3     21      2      2      1      1   
1621562   2006      2      2     17      2     31      1      1      1      1   
2213638   2009      1      3      9      3     36      2      4      3      1   
145284    1999      8      7      8      1      1      3      1      1      1   
3243660   2014      9      3     18      3     21      2      3      2      1   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
168721    1999     10      1      9      2     35      2      1      1      1   
2196356   2008     12      2     17      2     33      2      4      5      1   
2413177   2010      2      3     19      2     34      2      1      2      1   
3070209   2013      9      2      8      2     33      2      1      1      1   
1888484   2007      5      6      2      1      4      1      1      1      3   
1712853   2006      7      5     18      2     33      2      1      1      4   
2876706   2012      8      4     17      4     21      1      1      1      1   
2313890   2009      8      2     10      2     33      2      1      1      3   
1787698   2006     11      4      4      2     21      8      3      2      2   
3526199   2016      4      6     18      2     36      2      1      1      1   
2923138   2012     11      3      9      1      2      1      1      1      3   

        C_TRAF V_ID V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_SAFE P_USER  
1797192      1    1      1   1994    1     1    28    11      2      1  
704891      18    2      6   2000    1     1    44    11      2      1  
86650       18    1      6   1992    3     0    37    21      2      2  
932017      18    2      1   1995    2     0    12    13      2      2  
3131694     18    2      1   1997    3     0    50    11      2      1  
3114604      8    1      1   2008    1     0    66    11      2      1  
1746683      1    1      1   1996    1     1    30    11      2      1  
1621562     18    1      1   1998    1     1    52    11      2      1  
2213638      1    1      1   2004    1     1    22    11      2      1  
145284      18    1      1   1988    1     1    32    11      1      1  
3243660      3    3      1   2014    3     0    32    23      2      2  
...        ...  ...    ...    ...  ...   ...   ...   ...    ...    ...  
168721       3    1      1   1986    1     1    87    11      1      1  
2196356     18    1      1   2002    1     1    43    11      2      1  
2413177      3    1      1   1997    1     1    27    11      2      1  
3070209     18    1      1   2012    1     1    24    11      2      1  
1888484     18    1      1   2003    2     1    27    13      2      2  
1712853     18    2     14   1979    1     1    22    96      9      5  
2876706      1    2      1   2007    2     0    29    11      2      1  
2313890      3    1      1   2001    1     0    81    11      2      1  
1787698     18    2      1   2002    1     1    52    11      2      1  
3526199     18    1     14   2009    1     1    43    11      9      5  
2923138     18    1      1   2009    1     1    70    11      2      1  

[20773 rows x 20 columns]

1797192    1
704891     1
86650      2
932017     1
3131694    3
3114604    1
1746683    2
1621562    3
2213638    1
145284     2
3243660    1
          ..
168721     3
2196356    1
2413177    2
3070209    3
1888484    3
1712853    3
2876706    1
2313890    3
1787698    1
3526199    3
2923138    3
Name: P_ISEV, Length: 20773, dtype: category
Categories (3, int64): [1, 2, 3]

C_YEAR C_MNTH C_WDAY C_HOUR C_VEHS C_CONF C_RCFG C_WTHR C_RSUR C_RALN  \
2283890   2009      6      3     15      2     36      2      1      1      1   
1759599   2006     10      1     16      2     35      2      1      1      1   
390578    2000      9      4      6      2     31      1      2      2      4   
1834472   2007      2      3      8      3     21      1      1      1      1   
2783520   2012      2      1     16      2     35      2      1      1      2   
1537061   2005      9      5     17      2     36      3      1      2      2   
1278710   2004      7      5      3      1      4      1      2      1      3   
822953    2002      7      7     12      2     21      2      1      1      4   
2664314   2011      6      5     15      2     35      2      1      1      1   
1686272   2006      6      3     14      3     21      2      1      1      1   
2246507   2009      3      6     20      2     31      1      4      2      1   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2550203   2010     10      7     18      2     31      1      1      1      1   
720213    2002      2      4     10      2     36      2      1      1      2   
3519637   2016      4      3     18      2     32      1      4      3      6   
2344419   2009      9      7     12      3     21      2      1      1      1   
118884    1999      7      6     15      2     21      2      1      1      1   
368713    2000      8      4     18      2     33      2      1      1      1   
3312826   2015      1      7      5      2     31      1      5      5      3   
297466    2000      5      1     17      2     36      3      1      1      1   
3066255   2013      9      1     20      2     33      2      3      2      1   
131860    1999      8      3     17      2     21      5      1      1      1   
712388    2002      2      1      9      2     21      2      4      5      1   

        C_TRAF V_ID V_TYPE V_YEAR P_ID P_SEX P_AGE P_PSN P_SAFE P_USER  
2283890      1    1      1   2005    1     0    60    11      2      1  
1759599      3    1      9   2002    1     1    57    11      2      1  
390578      18    1      1   1995    1     1    27    11      2      1  
1834472     18    1      1   1995    1     1    28    11      2      1  
2783520      3    1     11   2007    5     1    47    32     13      2  
1537061      1    1      1   1989    1     1    55    11      2      1  
1278710     18    1      1   1994    1     1    50    11      1      1  
822953       4    1      1   1995    1     0    44    11      2      1  
2664314      3    2      1   2004    1     1    32    11      2      1  
1686272      1    3      1   2002    2     1    19    13      2      2  
2246507     18    1      1   1993    2     1    43    13      2      2  
...        ...  ...    ...    ...  ...   ...   ...   ...    ...    ...  
2550203     18    2      1   2003    1     1    72    11      2      1  
720213      18    1      1   2002    1     0    45    11      2      1  
3519637     18    2      1   2012    1     1    31    11      2      1  
2344419      1    1      1   1999    1     1    52    11      2      1  
118884      18    2      1   1994    1     0    55    11      2      1  
368713      18    2      1   1986    3     1     8    21      2      2  
3312826     18    1      1   2005    1     1    56    11      2      1  
297466      18    2      1   1988    1     1    45    11      2      1  
3066255      1    2     14   2005    1     1    16    11      9      5  
131860      18    1      1   1996    2     0    52    13      2      2  
712388       1    2      1   1991    1     1    38    11      2      1  

[48470 rows x 20 columns]

2283890    1
1759599    2
390578     3
1834472    1
2783520    3
1537061    1
1278710    3
822953     2
2664314    2
1686272    1
2246507    3
          ..
2550203    3
720213     1
3519637    2
2344419    1
118884     1
368713     2
3312826    3
297466     2
3066255    2
131860     2
712388     1
Name: P_ISEV, Length: 48470, dtype: category
Categories (3, int64): [1, 2, 3]

In [ ]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier

X = [[1,2], [2,4], [4,5], [3,2], [3,1]]
y = [0, 0, 1, 1, 2]
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

## Feature Selection

### Feature selection using Random Forest

## Logistic Regression Model

In [60]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=1000, random_state=0)
lr.fit(X_train, Y_train)

LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [61]:
y_pred = lr.predict(X_test)
#display(y_pred)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(lr.score(X_test, Y_test)))

Accuracy of logistic regression classifier on train set: 0.53
Accuracy of logistic regression classifier on test set: 0.54


In [62]:
# print the intercept (Note: one vs rest => 1 vs 2and3, 2 vs 1and3, 3 vs 1and2)
#lr.intercept_

In [63]:
# print the coeficients (Note: one vs rest => 1 vs 2and3, 2 vs 1and3, 3 vs 1and2)
#lr.coef_

In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[3796 1690 1522]
 [2193 2753 2077]
 [1007 1067 4668]]


In [65]:
# with L1 regularization
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='l1', C=1000, random_state=0)
lr.fit(X_train, Y_train)

LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [66]:
y_pred = lr.predict(X_test)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(lr.score(X_test, Y_test)))

from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

Accuracy of logistic regression classifier on train set: 0.54
Accuracy of logistic regression classifier on test set: 0.54
[[3772 1701 1535]
 [2193 2755 2075]
 [1020 1052 4670]]


### Support Vector Machines

In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', C=1, random_state=0)
svm.fit(X_train, Y_train)

In [ ]:
y_pred = svm.predict(X_test)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of SVM regression classifier on test set: {:.2f}'.format(svm.score(X_test, Y_test)))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

### Decison Tree

In [67]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='entropy',max_depth=5, random_state=0)
tree.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [68]:
y_pred = tree.predict(X_test)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of Tree classifier on test set: {:.2f}'.format(tree.score(X_test, Y_test)))

Accuracy of logistic regression classifier on train set: 0.54
Accuracy of Tree classifier on test set: 0.56


In [69]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[5173 1527  308]
 [3889 2408  726]
 [1306 1383 4053]]


### Random forest

In [70]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0, n_jobs=2)
forest.fit(X_train, Y_train)

C:\Users\pradeep\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [71]:
y_pred = forest.predict(X_test)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of RandomForest classifier on test set: {:.2f}'.format(forest.score(X_test, Y_test)))

Accuracy of logistic regression classifier on train set: 0.54
Accuracy of RandomForest classifier on test set: 0.60


In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[4533 1877  598]
 [2712 3046 1265]
 [ 764 1070 4908]]


In [73]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [74]:
y_pred = knn.predict(X_test)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(lr.score(X_train, Y_train)))
print('Accuracy of RandomForest classifier on test set: {:.2f}'.format(forest.score(X_test, Y_test)))

Accuracy of logistic regression classifier on train set: 0.54
Accuracy of RandomForest classifier on test set: 0.60


In [75]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[4026 2239  743]
 [3000 2536 1487]
 [1135 1343 4264]]
