In [19]:
import numpy as np
#in case we need to repeat experiment
np.random.seed(255)

import pandas as pd
pd.options.display.max_rows = 22

import matplotlib.pyplot as plt
plt.style.use('classic')


import seaborn as sns
sns.set()

In [20]:
#df = pd.read_csv('NCDB_2016.csv', engine = 'python')
df = pd.read_csv('data01_clean.csv', engine = 'python')

In [21]:
#df['P_SEX'] = df['P_SEX'].map({'F':0, 'M':1})

In [22]:
#df['P_ISEV'] = df['P_ISEV'].map({1:0, 2:1, 3:2})

In [23]:
df_cat = df.astype('category').copy()

In [24]:
#Split between train and test

X = df_cat.loc[:, df_cat.columns != 'P_ISEV'].copy()
Y = df_cat['P_ISEV']

In [25]:
#sprint into train and test 70/30
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [ ]:
X_test

In [17]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier

X = [[1,2], [2,4], [4,5], [3,2], [3,1]]
y = [0, 0, 1, 1, 2]
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

array([0, 0, 1, 1, 1])

## Logistic Regression Model

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
lr = OneVsRestClassifier(LogisticRegression(C=1000, random_state=0))
lr.fit(X_train, Y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [12]:
y_pred = lr.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(lr.score(X_test, Y_test)))

Accuracy of logistic regression classifier on test set: 0.63


In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[218163 256556      0]
 [145245 477814      0]
 [  1071   5903      0]]


### Support Vector Machines

In [ ]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
svm = OneVsRestClassifier(SVC(kernel='linear', C=1, random_state=0))
svm.fit(X_train.loc[0:20, : ], Y_train.loc[0:20])

In [ ]:
y_pred = svm.predict(X_test)
print('Accuracy of SVM regression classifier on test set: {:.2f}'.format(svm.score(X_test, Y_test)))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

### Decison Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.multiclass import OneVsRestClassifier
tree = OneVsRestClassifier(DecisionTreeClassifier(criterion='entropy',max_depth=5, random_state=0))
tree.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [14]:
y_pred = tree.predict(X_test)
print('Accuracy of Tree classifier on test set: {:.2f}'.format(tree.score(X_test, Y_test)))

Accuracy of Tree classifier on test set: 0.63


In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[321298 153421      0]
 [249864 373195      0]
 [  2104   4870      0]]


### Random forest

In [8]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0, n_jobs=2)
forest.fit(X_train, Y_train)

C:\Users\pradeep\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [10]:
y_pred = forest.predict(X_test)
print('Accuracy of RandomForest classifier on test set: {:.2f}'.format(forest.score(X_test, Y_test)))

Accuracy of RandomForest classifier on test set: 0.65


In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[301252 173415     52]
 [207309 415513    237]
 [  1132   5752     90]]
